# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      #- name: Setup Node.js environment
      #  uses: actions/setup-node@v1.4.3

      # Runs a single command using the runners shell
      - name: Npm install
        run: npm install
      
      - name: Lerna install packages
        run: node_modules/lerna/cli.js bootstrap
      
      - name: Lerna build packages
        run: node_modules/lerna/cli.js run build
        
      - name: Clean public folder
      - run: rm -rf public && mkdir public

      - name: Move dist packages
        shell: bash
        run: |
              for i in $(ls -d packages/*/dist/*) 
              do 
                cp -r $i public
              done
        
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: Public folder
          path: public

